// FROZEN golden master for Phase A2 (Slice 50), captured from garmentReport
// on origin/main at 27ef2c2 — BEFORE any stitch-based rewrite. This is recorded
// truth, not a live comparison: A2 replaces the functions that produced this data,
// so comparing against garmentReport itself post-rewrite would be comparing a
// thing to itself and would pass no matter what broke (COMPONENT-ARCHITECTURE.md
// discipline: a test that mirrors the output proves nothing). Every literal below
// was generated by running the REAL pre-rewrite garmentReport, not hand-typed.
//
// Regenerating this file is only ever correct BEFORE a behavior change, to record
// a new intentional truth — never AFTER, to make a broken build pass.
import { Report } from "../guidance/check";
import { Measurements } from "./measurements";
import { STANDARD_M } from "./measurements";

export const TEE_GOLDEN_POINTS: readonly Measurements[] = [
  STANDARD_M,
  { ...STANDARD_M, chest: 130, shoulderWidth: 50 },
  { ...STANDARD_M, chest: 70, shoulderWidth: 36, ease: 4 },
  { ...STANDARD_M, chest: 160 },
];

export const TEE_GOLDEN_REPORTS: readonly Report[] = [
  {
      ok: true,
      checks: [
        { name: "Shoulder seam (front \u2194 back)", ok: true, detail: "lengths agree (16.0 vs 16.0 cm)" },
        { name: "Side seam (front \u2194 back)", ok: true, detail: "lengths agree (46.0 vs 46.0 cm)" },
        { name: "Sleeve underarm (left \u2194 right)", ok: true, detail: "lengths agree (22.2 vs 22.2 cm)" },
        { name: "Sleeve-cap ease", ok: true, detail: "1.5 cm (within -1\u20134)" },
        { name: "Hem square to the fold", ok: true, detail: "90.0\u00b0 at the fold" },
        { name: "Notches + grainline on every piece", ok: true, detail: "all 3 pieces marked" },
        { name: "Size run grows in order", ok: true, detail: "5 sizes grow in order" },
      ],
    },
  {
      ok: true,
      checks: [
        { name: "Shoulder seam (front \u2194 back)", ok: true, detail: "lengths agree (17.0 vs 17.0 cm)" },
        { name: "Side seam (front \u2194 back)", ok: true, detail: "lengths agree (46.0 vs 46.0 cm)" },
        { name: "Sleeve underarm (left \u2194 right)", ok: true, detail: "lengths agree (22.2 vs 22.2 cm)" },
        { name: "Sleeve-cap ease", ok: true, detail: "1.5 cm (within -1\u20134)" },
        { name: "Hem square to the fold", ok: true, detail: "90.0\u00b0 at the fold" },
        { name: "Notches + grainline on every piece", ok: true, detail: "all 3 pieces marked" },
        { name: "Size run grows in order", ok: true, detail: "5 sizes grow in order" },
      ],
    },
  {
      ok: true,
      checks: [
        { name: "Shoulder seam (front \u2194 back)", ok: true, detail: "lengths agree (13.1 vs 13.1 cm)" },
        { name: "Side seam (front \u2194 back)", ok: true, detail: "lengths agree (46.0 vs 46.0 cm)" },
        { name: "Sleeve underarm (left \u2194 right)", ok: true, detail: "lengths agree (22.2 vs 22.2 cm)" },
        { name: "Sleeve-cap ease", ok: true, detail: "1.5 cm (within -1\u20134)" },
        { name: "Hem square to the fold", ok: true, detail: "90.0\u00b0 at the fold" },
        { name: "Notches + grainline on every piece", ok: true, detail: "all 3 pieces marked" },
        { name: "Size run grows in order", ok: true, detail: "5 sizes grow in order" },
      ],
    },
  {
      ok: true,
      checks: [
        { name: "Shoulder seam (front \u2194 back)", ok: true, detail: "lengths agree (13.1 vs 13.1 cm)" },
        { name: "Side seam (front \u2194 back)", ok: true, detail: "lengths agree (46.0 vs 46.0 cm)" },
        { name: "Sleeve underarm (left \u2194 right)", ok: true, detail: "lengths agree (22.2 vs 22.2 cm)" },
        { name: "Sleeve-cap ease", ok: true, detail: "1.5 cm (within -1\u20134)" },
        { name: "Hem square to the fold", ok: true, detail: "90.0\u00b0 at the fold" },
        { name: "Notches + grainline on every piece", ok: true, detail: "all 3 pieces marked" },
        { name: "Size run grows in order", ok: true, detail: "5 sizes grow in order" },
      ],
    },
];

export const FITTED_GOLDEN_POINTS: readonly Measurements[] = [
  STANDARD_M,
  { ...STANDARD_M, chest: 120, shoulderWidth: 48 },
  { ...STANDARD_M, chest: 76, shoulderWidth: 38 },
];

export const FITTED_GOLDEN_REPORTS: readonly Report[] = [
  {
      ok: true,
      checks: [
        { name: "Shoulder seam (front \u2194 back)", ok: true, detail: "lengths agree (16.0 vs 16.0 cm)" },
        { name: "Side seam (front \u2194 back)", ok: true, detail: "lengths agree (46.0 vs 46.0 cm)" },
        { name: "Sleeve underarm (left \u2194 right)", ok: true, detail: "lengths agree (22.2 vs 22.2 cm)" },
        { name: "Sleeve-cap ease", ok: true, detail: "1.5 cm (within -1\u20134)" },
        { name: "Dart legs equal", ok: true, detail: "lengths agree (12.5 vs 12.5 cm)" },
        { name: "Notches + grainline on every piece", ok: true, detail: "all 3 pieces marked" },
        { name: "Size run grows in order", ok: true, detail: "5 sizes grow in order" },
      ],
    },
  {
      ok: true,
      checks: [
        { name: "Shoulder seam (front \u2194 back)", ok: true, detail: "lengths agree (16.5 vs 16.5 cm)" },
        { name: "Side seam (front \u2194 back)", ok: true, detail: "lengths agree (46.0 vs 46.0 cm)" },
        { name: "Sleeve underarm (left \u2194 right)", ok: true, detail: "lengths agree (22.2 vs 22.2 cm)" },
        { name: "Sleeve-cap ease", ok: true, detail: "1.5 cm (within -1\u20134)" },
        { name: "Dart legs equal", ok: true, detail: "lengths agree (14.8 vs 14.8 cm)" },
        { name: "Notches + grainline on every piece", ok: true, detail: "all 3 pieces marked" },
        { name: "Size run grows in order", ok: true, detail: "5 sizes grow in order" },
      ],
    },
  {
      ok: true,
      checks: [
        { name: "Shoulder seam (front \u2194 back)", ok: true, detail: "lengths agree (13.8 vs 13.8 cm)" },
        { name: "Side seam (front \u2194 back)", ok: true, detail: "lengths agree (46.0 vs 46.0 cm)" },
        { name: "Sleeve underarm (left \u2194 right)", ok: true, detail: "lengths agree (22.2 vs 22.2 cm)" },
        { name: "Sleeve-cap ease", ok: true, detail: "2.3 cm (within -1\u20134)" },
        { name: "Dart legs equal", ok: true, detail: "lengths agree (9.9 vs 9.9 cm)" },
        { name: "Notches + grainline on every piece", ok: true, detail: "all 3 pieces marked" },
        { name: "Size run grows in order", ok: true, detail: "5 sizes grow in order" },
      ],
    },
];

export const SKIRT_GOLDEN_POINTS: readonly Measurements[] = [
  STANDARD_M,
  { ...STANDARD_M, waist: 70, hip: 96, hipDepth: 18 },
  { ...STANDARD_M, waist: 94, hip: 130, hipDepth: 25 },
];

// SKIRT_GOLDEN_REPORTS below was regenerated in Slice 57 (Phase B5) to record
// a new intentional truth \u2014 the skirt now really drafts a waistband \u2014 per
// this file's own rule: regenerating is only ever correct BEFORE a behaviour
// change, to record what changed on purpose, never after, to paper over a
// break. Every literal was generated by running the REAL post-Slice-57
// garmentReport(SKIRT, m), not hand-typed; see stitch.test.ts's "PRODUCTION
// skirt stitches" describe block for the same numbers proven independently.
export const SKIRT_GOLDEN_REPORTS: readonly Report[] = [
  {
      ok: true,
      checks: [
        { name: "Side seam (front \u2194 back)", ok: true, detail: "lengths agree (70.4 vs 70.4 cm)" },
        { name: "Waistband (front + back \u2194 waistband)", ok: true, detail: "lengths agree (47.0 vs 47.0 cm)" },
        { name: "Hem square to the fold", ok: true, detail: "90.0\u00b0 at the fold" },
        { name: "Waist square to the fold", ok: true, detail: "90.0\u00b0 at the fold" },
        { name: "Notches + grainline on every piece", ok: true, detail: "all 3 pieces marked" },
        { name: "Size run grows in order", ok: true, detail: "5 sizes grow in order" },
      ],
    },
  {
      ok: true,
      checks: [
        { name: "Side seam (front \u2194 back)", ok: true, detail: "lengths agree (71.1 vs 71.1 cm)" },
        { name: "Waistband (front + back \u2194 waistband)", ok: true, detail: "lengths agree (40.0 vs 40.0 cm)" },
        { name: "Hem square to the fold", ok: true, detail: "90.0\u00b0 at the fold" },
        { name: "Waist square to the fold", ok: true, detail: "90.0\u00b0 at the fold" },
        { name: "Notches + grainline on every piece", ok: true, detail: "all 3 pieces marked" },
        { name: "Size run grows in order", ok: true, detail: "5 sizes grow in order" },
      ],
    },
  {
      ok: true,
      checks: [
        { name: "Side seam (front \u2194 back)", ok: true, detail: "lengths agree (71.6 vs 71.6 cm)" },
        { name: "Waistband (front + back \u2194 waistband)", ok: true, detail: "lengths agree (52.0 vs 52.0 cm)" },
        { name: "Hem square to the fold", ok: true, detail: "90.0\u00b0 at the fold" },
        { name: "Waist square to the fold", ok: true, detail: "90.0\u00b0 at the fold" },
        { name: "Notches + grainline on every piece", ok: true, detail: "all 3 pieces marked" },
        { name: "Size run grows in order", ok: true, detail: "5 sizes grow in order" },
      ],
    },
];
